// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{0}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponse struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{1}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutDataRequest) Reset()         { *m = PutDataRequest{} }
func (m *PutDataRequest) String() string { return proto.CompactTextString(m) }
func (*PutDataRequest) ProtoMessage()    {}
func (*PutDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{2}
}

func (m *PutDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutDataRequest.Unmarshal(m, b)
}
func (m *PutDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutDataRequest.Marshal(b, m, deterministic)
}
func (m *PutDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutDataRequest.Merge(m, src)
}
func (m *PutDataRequest) XXX_Size() int {
	return xxx_messageInfo_PutDataRequest.Size(m)
}
func (m *PutDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutDataRequest proto.InternalMessageInfo

func (m *PutDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutDataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutDataResponse) Reset()         { *m = PutDataResponse{} }
func (m *PutDataResponse) String() string { return proto.CompactTextString(m) }
func (*PutDataResponse) ProtoMessage()    {}
func (*PutDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{3}
}

func (m *PutDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutDataResponse.Unmarshal(m, b)
}
func (m *PutDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutDataResponse.Marshal(b, m, deterministic)
}
func (m *PutDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutDataResponse.Merge(m, src)
}
func (m *PutDataResponse) XXX_Size() int {
	return xxx_messageInfo_PutDataResponse.Size(m)
}
func (m *PutDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutDataResponse proto.InternalMessageInfo

type Data struct {
	StringShape          string         `protobuf:"bytes,1,opt,name=StringShape,json=stringShape,proto3" json:"StringShape,omitempty"`
	IntShape             int32          `protobuf:"varint,2,opt,name=IntShape,json=intShape,proto3" json:"IntShape,omitempty"`
	DoubleShape          float64        `protobuf:"fixed64,3,opt,name=DoubleShape,json=doubleShape,proto3" json:"DoubleShape,omitempty"`
	BoolShape            bool           `protobuf:"varint,4,opt,name=BoolShape,json=boolShape,proto3" json:"BoolShape,omitempty"`
	BytesShape           []byte         `protobuf:"bytes,5,opt,name=BytesShape,json=bytesShape,proto3" json:"BytesShape,omitempty"`
	Shapes               []*NestedShape `protobuf:"bytes,6,rep,name=Shapes,json=shapes,proto3" json:"Shapes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetStringShape() string {
	if m != nil {
		return m.StringShape
	}
	return ""
}

func (m *Data) GetIntShape() int32 {
	if m != nil {
		return m.IntShape
	}
	return 0
}

func (m *Data) GetDoubleShape() float64 {
	if m != nil {
		return m.DoubleShape
	}
	return 0
}

func (m *Data) GetBoolShape() bool {
	if m != nil {
		return m.BoolShape
	}
	return false
}

func (m *Data) GetBytesShape() []byte {
	if m != nil {
		return m.BytesShape
	}
	return nil
}

func (m *Data) GetShapes() []*NestedShape {
	if m != nil {
		return m.Shapes
	}
	return nil
}

type NestedShape struct {
	NestedInt            int32    `protobuf:"varint,1,opt,name=NestedInt,json=nestedInt,proto3" json:"NestedInt,omitempty"`
	NestedBytes          []byte   `protobuf:"bytes,2,opt,name=NestedBytes,json=nestedBytes,proto3" json:"NestedBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NestedShape) Reset()         { *m = NestedShape{} }
func (m *NestedShape) String() string { return proto.CompactTextString(m) }
func (*NestedShape) ProtoMessage()    {}
func (*NestedShape) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{5}
}

func (m *NestedShape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedShape.Unmarshal(m, b)
}
func (m *NestedShape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedShape.Marshal(b, m, deterministic)
}
func (m *NestedShape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedShape.Merge(m, src)
}
func (m *NestedShape) XXX_Size() int {
	return xxx_messageInfo_NestedShape.Size(m)
}
func (m *NestedShape) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedShape.DiscardUnknown(m)
}

var xxx_messageInfo_NestedShape proto.InternalMessageInfo

func (m *NestedShape) GetNestedInt() int32 {
	if m != nil {
		return m.NestedInt
	}
	return 0
}

func (m *NestedShape) GetNestedBytes() []byte {
	if m != nil {
		return m.NestedBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDataRequest)(nil), "models.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "models.GetDataResponse")
	proto.RegisterType((*PutDataRequest)(nil), "models.PutDataRequest")
	proto.RegisterType((*PutDataResponse)(nil), "models.PutDataResponse")
	proto.RegisterType((*Data)(nil), "models.Data")
	proto.RegisterType((*NestedShape)(nil), "models.NestedShape")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_0984d49a362b6b9f) }

var fileDescriptor_0984d49a362b6b9f = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xed, 0xfe, 0xd2, 0xe4, 0xd7, 0xcc, 0x96, 0x56, 0x57, 0xd0, 0x52, 0x44, 0x96, 0x9c, 0x02,
	0x42, 0x0f, 0xed, 0xd5, 0x53, 0x29, 0x48, 0x11, 0x45, 0xb6, 0x9f, 0x20, 0x21, 0x83, 0x16, 0xeb,
	0x6e, 0xed, 0x6e, 0x0e, 0x39, 0xfb, 0x09, 0xfd, 0x46, 0xb2, 0xbb, 0xf9, 0x63, 0x15, 0xbd, 0x65,
	0xde, 0x9b, 0xf7, 0x66, 0x67, 0x5e, 0x80, 0x1e, 0x54, 0x69, 0x70, 0xb6, 0x3f, 0x28, 0xa3, 0x58,
	0xf4, 0xaa, 0x0a, 0xdc, 0xe9, 0x24, 0x81, 0xd1, 0x2d, 0x9a, 0x55, 0x66, 0x32, 0x81, 0x6f, 0x25,
	0x6a, 0xc3, 0x4e, 0x20, 0xb8, 0xc3, 0x6a, 0x42, 0x38, 0x49, 0x63, 0x11, 0xbc, 0x60, 0x95, 0x2c,
	0x60, 0xdc, 0xf6, 0xe8, 0xbd, 0x92, 0x1a, 0x19, 0x87, 0xbe, 0xad, 0x5d, 0x17, 0x9d, 0x0f, 0x67,
	0xde, 0x6d, 0xe6, 0x7a, 0xfa, 0x45, 0x66, 0xb2, 0x64, 0x05, 0xa3, 0xc7, 0xf2, 0x6f, 0xe3, 0xd6,
	0xe5, 0xdf, 0xaf, 0x2e, 0xa7, 0x30, 0x6e, 0x5d, 0xfc, 0xe8, 0xe4, 0x83, 0x78, 0x15, 0xe3, 0x40,
	0x37, 0xe6, 0xb0, 0x95, 0x4f, 0x9b, 0xe7, 0x6c, 0x8f, 0xb5, 0x2f, 0xd5, 0x1d, 0xc4, 0xa6, 0x30,
	0x58, 0x4b, 0xe3, 0x69, 0x3b, 0x23, 0x14, 0x83, 0x6d, 0x5d, 0x5b, 0xf5, 0x4a, 0x95, 0xf9, 0x0e,
	0x3d, 0x1d, 0x70, 0x92, 0x12, 0x41, 0x8b, 0x0e, 0x62, 0x97, 0x10, 0x2f, 0x95, 0xda, 0x79, 0xbe,
	0xcf, 0x49, 0x3a, 0x10, 0x71, 0xde, 0x00, 0xec, 0x0a, 0x60, 0x59, 0x19, 0xd4, 0x9e, 0x0e, 0x39,
	0x49, 0x87, 0x02, 0xf2, 0x16, 0x61, 0xd7, 0x10, 0xb9, 0x0f, 0x3d, 0x89, 0x78, 0x90, 0xd2, 0xf9,
	0x59, 0xb3, 0xdd, 0x03, 0x6a, 0x83, 0x85, 0xe3, 0x44, 0xa4, 0x5d, 0x4b, 0x72, 0x0f, 0xf4, 0x0b,
	0x6c, 0x27, 0xfb, 0x72, 0x2d, 0x8d, 0xdb, 0x2b, 0x14, 0xb1, 0x6c, 0x00, 0xfb, 0x72, 0xcf, 0xba,
	0xf9, 0x6e, 0xb1, 0xa1, 0xa0, 0xb2, 0x83, 0xe6, 0xef, 0x04, 0x42, 0x61, 0xc3, 0x66, 0x37, 0xf0,
	0xbf, 0x8e, 0x8e, 0x9d, 0x37, 0x0f, 0x38, 0xce, 0x7b, 0x7a, 0xf1, 0x03, 0xaf, 0x0f, 0xdd, 0xb3,
	0xea, 0xfa, 0xfa, 0x9d, 0xfa, 0x38, 0xd4, 0x4e, 0xfd, 0x3d, 0xa6, 0x5e, 0x1e, 0xb9, 0x3f, 0x6d,
	0xf1, 0x19, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x6b, 0xc4, 0xcf, 0x78, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteClient is the client API for Route service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	PutData(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error)
}

type routeClient struct {
	cc *grpc.ClientConn
}

func NewRouteClient(cc *grpc.ClientConn) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/models.Route/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) PutData(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error) {
	out := new(PutDataResponse)
	err := c.cc.Invoke(ctx, "/models.Route/PutData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServer is the server API for Route service.
type RouteServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	PutData(context.Context, *PutDataRequest) (*PutDataResponse, error)
}

func RegisterRouteServer(s *grpc.Server, srv RouteServer) {
	s.RegisterService(&_Route_serviceDesc, srv)
}

func _Route_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Route/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_PutData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).PutData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Route/PutData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).PutData(ctx, req.(*PutDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Route_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Route",
	HandlerType: (*RouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Route_GetData_Handler,
		},
		{
			MethodName: "PutData",
			Handler:    _Route_PutData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}
